# Generated by Django 3.2.9 on 2021-12-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_name', models.CharField(max_length=30)),
                ('current_amt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fill_amt', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('store_longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('store_latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('amt_1', models.IntegerField()),
                ('amt_2', models.IntegerField()),
                ('amt_3', models.IntegerField()),
                ('amt_4', models.IntegerField()),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='globalspend_app.envelope')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('original_transaction_amt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('home_transaction_amt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_type', models.BooleanField()),
                ('notes', models.TextField()),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='globalspend_app.envelope')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='globalspend_app.store')),
            ],
        ),
    ]
