# Generated by Django 3.2.9 on 2021-12-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalspend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='is_debit_transaction',
        ),
    ]
