# Generated by Django 3.2.9 on 2021-12-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalspend_app', '0003_auto_20211215_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_debit_transaction',
            field=models.BooleanField(default=True),
        ),
    ]
