# Generated by Django 3.2.9 on 2021-12-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalspend_app', '0004_alter_transaction_is_debit_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
