# Generated by Django 3.2.9 on 2021-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalspend_app', '0005_alter_transaction_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='envelope',
        ),
        migrations.AddField(
            model_name='store',
            name='envelope',
            field=models.ManyToManyField(related_name='store', to='globalspend_app.Envelope'),
        ),
    ]
